### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by nileshtrivedi** [prrockzed/chessed#1]
First of all, thanks for making this and open-sourcing it. I find it very cumbersome to play on chess.com when all players are in the same room. This should help a lot.

Having said that, a few enhancements would be great to have:

- Highlight the king when it is under check
- Per-player clock
- Instead of dragging the piece, many kids prefer clicking first the piece and then clicking  the destination square.
- Don't finish the game when one player gets checkmated.

**Comment by prrockzed** [comment]
Hi Nilesh! Glad that you showed interest in the project.

Thanks for the ideas(quite good ones infact). I would try to implement these changes in the upcoming days(though i have some college exams currently so it might be a bit late).
But i would be more than happy to have you as a collaborator, if you are interested.

**Comment by nileshtrivedi** [comment]
Yeah, I can try to help. Though when I ran `npm run start`, pieces didn't load. I think it's because requests are being made to `http://localhost:3000/assets/images/rQ.png/` instead of 'http://localhost:3000/four-player-chess/assets/images/rQ.png`

**Comment by prrockzed** [comment]
Ig, I have fixed the issue now.

**Comment by prrockzed** [comment]
Just a little update to all your ideas.
I am planning to register this project in some open source programs so that new contributors can join in to make the project better. Thus, I am turning all of the suggestions you have given to new and separate issues.
