### ISSUE TITLE
Don't finish the game when one player is checkmated

### ISSUE THREAD

**Issue by prrockzed** [prrockzed/chessed#3]
### **Is your feature request related to a problem? Please describe.**  
Currently, the game ends as soon as one player gets checkmated. This limits the experience, as the remaining players are unable to continue the game and determine their rankings. It feels abrupt and doesn't allow a full progression of the match.

### **Describe the solution you'd like**  
Allow the game to continue even after one player is checkmated. The match should proceed until only one player remains. At the end, display the final rankings for all players, determined by the order in which they were checkmated (e.g., the first player checkmated would rank last, and so on).

### **Additional Context**  
This enhancement would make the gameplay more dynamic and competitive, as all players get a chance to see their standings. For example, showing a final scoreboard at the end could improve user satisfaction.

**Comment by kartikmax** [comment]
Hi can we add the score-based system, so that we can allow other three players to continue the game. 
For example we can use the rules which chess.com uses in its game like +1 for pawn , +3 for knight, +5 for the rook and bishop and +9 for queen

**Comment by dipamsen** [comment]
I don't think that's relevant to resolve this issue, leaderboard should be shown based on order in which the players get checkmated. The winner is the player who is the last man standing, second is whoever got checkmated the last, and so on...

**Comment by prrockzed** [comment]
Yeah, I agree with Dipamsem.

I think there are too many faults with the number system that chess.com uses and ranking players according to the points they collect. So, I think it will be better to keep scoreboard as mentioned above.

As to what happens to the pieces(once someone gets checkmated), i haven't really thought about that. Actually we can keep the pieces but make them dull(and to do that we need to upload another set of grey/dull pieces) and they will be on the board until someone captures them(similar to chess.com). Or another idea is to completely remove them as they don't have any significance on the board. They ain't contributing to literally anything. Am open to both the ideas!

As for this issue, we need to keep the game going till last person remains, skip the person's move who got checkmated, and do something with the damn checkmated pieces(Choose one of the options from the previous para). Display a small scorecard(with nice ui ofc) beside the chess board. The scorecard will be dynamically updated as the players gets checkmated. The design and position of the scorecard is left to the creativity of the contributor. Finally when the game ends, display the scorecard on top of the board.
