### ISSUE TITLE
Highlight the king when it's checked

### ISSUE THREAD

**Issue by prrockzed** [prrockzed/chessed#5]
### **Is your feature request related to a problem? Please describe.**  
Currently, the game logic correctly identifies when a king is in check(that is only the king and related pieces can move to save the king), but there is no visual indication of this on the board. This makes it less intuitive for players to notice when their king is in danger.

### **Describe the solution you'd like**  
Highlight the king's square with a distinct color as soon as it is in check. This will provide immediate visual feedback to the player, making it clear that their king is under threat. It is a simple css implementation. This highlight will only be shown when it's the move of the checked king and not for any other player.

### **Additional Context**  
This feature will enhance the game's usability by improving player awareness during critical moments. For instance, using a red or orange background for the checked king's square would be a simple yet effective way to highlight it without disrupting the overall board design.

**Comment by Ajayendra2705** [comment]
Hi, Can I take up this issue?

**Comment by Priyanshiagarwal2006** [comment]
Hi. I would like to work in this issue. Could you assign it to me. As I  am a chess player I would like to contribute in this.

**Comment by Priyanshiagarwal2006** [comment]
To highlight a king when it is in check in a chess game, you'll need a way to:

Determine if the king is in check.
Identify the square containing the king.

**SOME **STEPS****

 Determine if the King is in Check.
 Identify the King's Square.
 Highlight the Square.

I would like to work in this issue. Could you assign it to me. Looking forward to  `Contrbuting!`

**Comment by Priyanshiagarwal2006** [comment]
`function highlightCheckedKing() {
  if (isKingInCheck()) {
    const color = chess.turn(); // Get the color of the current player's king
    const kingSquare = getKingSquare(color);
    if (kingSquare) {
      const squareElement = document.getElementById(kingSquare);
      if (squareElement) {
        squareElement.classList.add('check');
      }
    }
  }
}

// Example usage
highlightCheckedKing();

**Comment by Bhoomish-Patel** [comment]
### Hi,

I’d love to work on the issue of highlighting the king’s square when it is in check. Here’s my proposed plan:

### Logic for King’s Check:
- **`get isKingChecked()` function**: I’ve updated this function to check if the king is in check. It simulates the board, finds the king's position, and checks if any enemy pieces can move to the king’s square.
  
  ```ts
  get isKingChecked() {
    const simulatedBoard = this.clone();
    const king = simulatedBoard.pieces.find((p) => p.isKing && p.team === simulatedBoard.currentTeam)!;
    
    for (const enemy of simulatedBoard.pieces.filter((p) => { return p.team !== simulatedBoard.currentTeam })) {
      enemy.possibleMoves = simulatedBoard.getValidMoves(enemy, simulatedBoard.pieces);
      
      if (enemy.possibleMoves?.some((m) => {
        return m.samePosition(king.position);
      })) {
        return true;
      }
    }
    return false;
  }

### Highlighting the King’s Square:
In `board.ts`, I added logic to highlight the king's square when the king is in check. The tile is highlighted in red if the king is under threat.

```tsx
const isKingTile = isKingChecked && CurrentKingPos?.samePosition(new Position(i, j));

board.push(
  <Tile
    key={`${i},${j}`}
    num_i={num_i}
    num_j={num_j}
    image={image}
    highlight={highlight}
    style={{
      backgroundColor: isKingTile ? 'red' : undefined, 
    }}
  />
);
The king's square will only be highlighted when it’s the current player’s move to ensure no visual disruption when the other player is active.
```

This change provides immediate visual feedback to players, making it clear when their king is in danger.

Let me know if this approach looks good, and if so, please assign me the issue! Looking forward to contributing! 


![Screenshot 2024-12-10 215308](https://github.com/user-attachments/assets/da4f619a-5a22-45da-bdf4-53813577bc70)

**Comment by prrockzed** [comment]
Great work guys! Now just make a pull request, so i that i can merge this.
